apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-githuboss-settings
spec:
  forms:
    - group: health
      label: 健康检查
      formSchema:
        - $formkit: text
          name: status
          label: 状态
          value: "未检查"