# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: plugin-githuboss
spec:
  enabled: true
  requires: ">=2.21.0"
  author:
    name: xirizhi
    website: https://xirizhi.cn
  logo: logo.jpg
  settingName: plugin-githuboss-settings
  configMapName: plugin-githuboss-configMap
  homepage: https://github.com/xirizhi/plugin-githuboss#readme
  repo: https://github.com/guicaiyue/plugin-githuboss
  issues: https://github.com/guicaiyue/plugin-githuboss/issues
  displayName: "Github附件插件"
  description: "使用Github存放附件的插件"
  license:
    - name: "GPL-3.0"
