name: Build Plugin JAR File

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 21
      - name: Setup pnpm 9.15.9
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
          run_install: false
      - name: Build with Gradle
        run: |
          # Set the version with tag name when releasing
          version=${{ github.event.release.tag_name }}
          version=${version#v}
          sed -i "s/version=.*-SNAPSHOT$/version=$version/1" gradle.properties
          ./gradlew clean build -x test
      - name: Archive plugin-githuboss jar
        uses: actions/upload-artifact@v4
        with:
          name: plugin-githuboss
          path: |
            build/libs/*.jar
          retention-days: 1

  github-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Download plugin-githuboss jar
        uses: actions/download-artifact@v4
        with:
          name: plugin-githuboss
          path: build/libs
      - name: Upload Release Asset (softprops)
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: build/libs/*.jar
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
